POST http://127.0.0.30:8080
Accept: */*
Cache-Control: no-cache
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="100.png";

< ./storage-service/src/test/resources/100.png

--boundary--
###
