version: '3'
services:
  minio:
    image: minio/minio
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - ${APP_HOST}:9000:9000
    volumes:
      - ./data:/data
    command: 'server /data'
volumes:
  minio-data:
    driver: local
