name: Checking build&tests
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Start containers
      run: docker compose up -d
    - name: Build and test
      run: ./gradlew build
